package com.endava.budgetplanner

import com.endava.budgetplanner.common.ext.filterByType
import com.endava.budgetplanner.common.utils.CategoryProperties
import com.endava.budgetplanner.common.utils.TransactionType
import com.endava.budgetplanner.data.models.Category
import com.endava.budgetplanner.models.CategoriesFilterCase
import org.junit.Assert.assertEquals
import org.junit.Test
import org.junit.runner.RunWith
import org.junit.runners.Parameterized

@RunWith(Parameterized::class)
class CategoriesFilterTest(private val case: CategoriesFilterCase) {

    @Test
    fun `check if after filter and sorting category Other will be at the end of the list`() {
        val categories = case.categories.filterByType(case.type)
        assertEquals(categories, case.expected)
    }

    companion object {

        @JvmStatic
        @Parameterized.Parameters(name = "{0}-Categories {1}-Type {2}-Expected")
        fun setParameters() = listOf(
            CategoriesFilterCase(
                listOf(
                    Category(
                        1,
                        "Food",
                        CategoryProperties.FOOD,
                        TransactionType.EXPENSES,
                        2500.25,
                        15,
                        "color"
                    ),
                    Category(
                        1,
                        "Entertainment",
                        CategoryProperties.ENTERTAINMENT,
                        TransactionType.EXPENSES,
                        2500.25,
                        15,
                        "color"
                    ),
                    Category(
                        1,
                        "Other",
                        CategoryProperties.OTHER,
                        TransactionType.EXPENSES,
                        2500.25,
                        15,
                        "color"
                    ),
                    Category(
                        1,
                        "Taxes",
                        CategoryProperties.TAXES,
                        TransactionType.EXPENSES,
                        2500.25,
                        15,
                        "color"
                    ),
                    Category(
                        1,
                        "Shopping",
                        CategoryProperties.SHOPPING,
                        TransactionType.EXPENSES,
                        2500.25,
                        15,
                        "color"
                    ),
                    Category(
                        1,
                        "Sport",
                        CategoryProperties.SPORT,
                        TransactionType.EXPENSES,
                        2500.25,
                        15,
                        "color"
                    ),
                    Category(
                        1,
                        "Investments",
                        CategoryProperties.INVESTMENTS,
                        TransactionType.INCOME,
                        2500.25,
                        15,
                        "color"
                    ),
                    Category(
                        1,
                        "Salaries",
                        CategoryProperties.SALARIES,
                        TransactionType.INCOME,
                        2500.25,
                        15,
                        "color"
                    ),
                    Category(
                        1,
                        "Payments",
                        CategoryProperties.PAYMENTS,
                        TransactionType.INCOME,
                        2500.25,
                        15,
                        "color"
                    ),
                    Category(
                        1,
                        "Other",
                        CategoryProperties.OTHER,
                        TransactionType.INCOME,
                        2500.25,
                        15,
                        "color"
                    )
                ),
                TransactionType.EXPENSES,
                listOf(
                    Category(
                        1,
                        "Entertainment",
                        CategoryProperties.ENTERTAINMENT,
                        TransactionType.EXPENSES,
                        2500.25,
                        15,
                        "color"
                    ),
                    Category(
                        1,
                        "Food",
                        CategoryProperties.FOOD,
                        TransactionType.EXPENSES,
                        2500.25,
                        15,
                        "color"
                    ),
                    Category(
                        1,
                        "Shopping",
                        CategoryProperties.SHOPPING,
                        TransactionType.EXPENSES,
                        2500.25,
                        15,
                        "color"
                    ),
                    Category(
                        1,
                        "Sport",
                        CategoryProperties.SPORT,
                        TransactionType.EXPENSES,
                        2500.25,
                        15,
                        "color"
                    ),
                    Category(
                        1,
                        "Taxes",
                        CategoryProperties.TAXES,
                        TransactionType.EXPENSES,
                        2500.25,
                        15,
                        "color"
                    ),
                    Category(
                        1,
                        "Other",
                        CategoryProperties.OTHER,
                        TransactionType.EXPENSES,
                        2500.25,
                        15,
                        "color"
                    )
                )
            ),
            CategoriesFilterCase(
                listOf(
                    Category(
                        1,
                        "Food",
                        CategoryProperties.FOOD,
                        TransactionType.EXPENSES,
                        2500.25,
                        15,
                        "color"
                    ),
                    Category(
                        1,
                        "Entertainment",
                        CategoryProperties.ENTERTAINMENT,
                        TransactionType.EXPENSES,
                        2500.25,
                        15,
                        "color"
                    ),
                    Category(
                        1,
                        "Taxes",
                        CategoryProperties.TAXES,
                        TransactionType.EXPENSES,
                        2500.25,
                        15,
                        "color"
                    ),
                    Category(
                        1,
                        "Shopping",
                        CategoryProperties.SHOPPING,
                        TransactionType.EXPENSES,
                        2500.25,
                        15,
                        "color"
                    ),
                    Category(
                        1,
                        "Sport",
                        CategoryProperties.SPORT,
                        TransactionType.EXPENSES,
                        2500.25,
                        15,
                        "color"
                    ),
                    Category(
                        1,
                        "Other",
                        CategoryProperties.OTHER,
                        TransactionType.EXPENSES,
                        2500.25,
                        15,
                        "color"
                    ),
                    Category(
                        1,
                        "Investments",
                        CategoryProperties.INVESTMENTS,
                        TransactionType.INCOME,
                        2500.25,
                        15,
                        "color"
                    ),
                    Category(
                        1,
                        "Salaries",
                        CategoryProperties.SALARIES,
                        TransactionType.INCOME,
                        2500.25,
                        15,
                        "color"
                    ),
                    Category(
                        1,
                        "Payments",
                        CategoryProperties.PAYMENTS,
                        TransactionType.INCOME,
                        2500.25,
                        15,
                        "color"
                    ),
                    Category(
                        1,
                        "Other",
                        CategoryProperties.OTHER,
                        TransactionType.INCOME,
                        2500.25,
                        15,
                        "color"
                    )
                ),
                TransactionType.INCOME,
                listOf(
                    Category(
                        1,
                        "Investments",
                        CategoryProperties.INVESTMENTS,
                        TransactionType.INCOME,
                        2500.25,
                        15,
                        "color"
                    ),
                    Category(
                        1,
                        "Payments",
                        CategoryProperties.PAYMENTS,
                        TransactionType.INCOME,
                        2500.25,
                        15,
                        "color"
                    ),
                    Category(
                        1,
                        "Salaries",
                        CategoryProperties.SALARIES,
                        TransactionType.INCOME,
                        2500.25,
                        15,
                        "color"
                    ),
                    Category(
                        1,
                        "Other",
                        CategoryProperties.OTHER,
                        TransactionType.INCOME,
                        2500.25,
                        15,
                        "color"
                    )
                )
            ),
            CategoriesFilterCase(
                listOf(
                    Category(
                        1,
                        "Food",
                        CategoryProperties.FOOD,
                        TransactionType.EXPENSES,
                        2500.25,
                        15,
                        "color"
                    ),
                    Category(
                        1,
                        "Shopping",
                        CategoryProperties.SHOPPING,
                        TransactionType.EXPENSES,
                        2500.25,
                        15,
                        "color"
                    ),
                    Category(
                        1,
                        "Entertainment",
                        CategoryProperties.ENTERTAINMENT,
                        TransactionType.EXPENSES,
                        2500.25,
                        15,
                        "color"
                    ),
                    Category(
                        1,
                        "Taxes",
                        CategoryProperties.TAXES,
                        TransactionType.EXPENSES,
                        2500.25,
                        15,
                        "color"
                    ),
                    Category(
                        1,
                        "Sport",
                        CategoryProperties.SPORT,
                        TransactionType.EXPENSES,
                        2500.25,
                        15,
                        "color"
                    ),
                    Category(
                        1,
                        "Investments",
                        CategoryProperties.INVESTMENTS,
                        TransactionType.INCOME,
                        2500.25,
                        15,
                        "color"
                    ),
                    Category(
                        1,
                        "Salaries",
                        CategoryProperties.SALARIES,
                        TransactionType.INCOME,
                        2500.25,
                        15,
                        "color"
                    ),
                    Category(
                        1,
                        "Payments",
                        CategoryProperties.PAYMENTS,
                        TransactionType.INCOME,
                        2500.25,
                        15,
                        "color"
                    ),
                    Category(
                        1,
                        "Other",
                        CategoryProperties.OTHER,
                        TransactionType.INCOME,
                        2500.25,
                        15,
                        "color"
                    )
                ),
                TransactionType.EXPENSES,
                listOf(
                    Category(
                        1,
                        "Entertainment",
                        CategoryProperties.ENTERTAINMENT,
                        TransactionType.EXPENSES,
                        2500.25,
                        15,
                        "color"
                    ),
                    Category(
                        1,
                        "Food",
                        CategoryProperties.FOOD,
                        TransactionType.EXPENSES,
                        2500.25,
                        15,
                        "color"
                    ),
                    Category(
                        1,
                        "Shopping",
                        CategoryProperties.SHOPPING,
                        TransactionType.EXPENSES,
                        2500.25,
                        15,
                        "color"
                    ),
                    Category(
                        1,
                        "Sport",
                        CategoryProperties.SPORT,
                        TransactionType.EXPENSES,
                        2500.25,
                        15,
                        "color"
                    ),
                    Category(
                        1,
                        "Taxes",
                        CategoryProperties.TAXES,
                        TransactionType.EXPENSES,
                        2500.25,
                        15,
                        "color"
                    )
                )
            )
        )
    }
}